### ISSUE TITLE
Building with Docker fails

### ISSUE THREAD

**Issue by rdagher** [xebia-france/code-elevator#28]
Hi,

I wanted to test the code-elevator server using Docker. The `build.sh` fails because of a test failure in (`WebResourceTest.java`). See [attachement](https://github.com/xebia-france/code-elevator/files/456372/docker_mvn_build_output.txt).

For finishing the build and have the container ready, I had to ignore this test by adding these lines to the [code-elevator/elevator-server/pom.xml](https://github.com/xebia-france/code-elevator/blob/master/elevator-server/pom.xml#L97):
```xml
                <plugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-surefire-plugin</artifactId>
                  <version>2.12.4</version>
                  <configuration>
                    <excludes>
                      <exclude>**/WebResourceTest.java</exclude>
                    </excludes>
                  </configuration>
                </plugin>
````

Any idea how to make this test pass?

Best,
Roudy

**Comment by seblm** [comment]
Thank you for your feedback.
It works on my machine® with a local java/maven but you're right: issue is reproduced into docker. I'll check why and try to fix it as soon as possible.

**Comment by seblm** [comment]
It appears that this issue is randomly encountered. Both local java/maven build and into docker container sometimes fails. There is [an open issue](https://java.net/jira/browse/JERSEY-2627) about this bug introduced after Jersey 2.9.
Can you tell me if you are able successfully build a docker image after a _reasonable_ number of tries?

**Comment by rdagher** [comment]
@seblm I have tried several times, and never succeeded to build an image.
Note that, locally (on my machine) I never experienced any failures (`mvn verify`).

**Comment by seblm** [comment]
_Web tests_ aren't relying on jetty container anymore: they'll only use jersey on embedded jdk http engine. So issue will maybe never occurs anymore. Can you please confirm?

**Comment by rdagher** [comment]
Works great now, thanks for the update !
